### ISSUE TITLE
Bot Keyboard

### ISSUE THREAD

**Issue by Igordeveloperr** [Sparrow1488/Nude#11]
## todo по клавиатуре
+ [ ] создать все клавиатуры и вынести их в отдельный статический класс
+ [ ] связать каждую кнопку с ее командой
+ [ ] реализовать переключение между клавиатурами(смена уровня) с помощью добавления вспомогательных endpoints
